# Setup
title:               Blog
tagline:             'De Xerionte'
description:         'Anotaciones de ciberseguridad en las comunicaciones e IT '
url:
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

highlighter: rouge


# Custom vars
version:             1.1.0
google_analytics_id: G-350X27F3BM
